# Generated by Django 4.2.8 on 2023-12-18 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0007_journalentry_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='user',
        ),
        migrations.AddField(
            model_name='journal',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.journalentry'),
        ),
    ]
