# Generated by Django 4.2.8 on 2023-12-18 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zohoapp', '0008_remove_journalentry_journal_remove_journalentry_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='journal',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.journal'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='journal',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='cash_journal',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='currency',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='difference',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='journal_no',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='reference_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('save', 'Save')], default='draft', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='total_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='total_debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='account',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='credits',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='debits',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
