# Generated by Django 4.2.8 on 2023-12-18 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0010_remove_journalentry_journal_journal_journal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='journal',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.journal'),
        ),
    ]
