# Generated by Django 4.2.8 on 2023-12-18 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0011_remove_journal_journal_journalentry_journal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='user',
        ),
    ]
