# Generated by Django 4.2.8 on 2023-12-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0013_journal_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='account',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='debits',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='description',
        ),
        migrations.AddField(
            model_name='journal',
            name='account',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='contact',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='credits',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='debits',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
