# Generated by Django 4.2.8 on 2023-12-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0016_remove_journalentry_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='reference_no',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
