# Generated by Django 4.2.8 on 2023-12-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0018_alter_journal_reference_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='reference_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
