# Generated by Django 4.2.8 on 2024-01-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0019_alter_journal_reference_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='account',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='debits',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='description',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='account',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='contact',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='credits',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='debits',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
