# Generated by Django 4.2.8 on 2024-01-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0020_remove_journal_account_remove_journal_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='first_journal_entry',
            field=models.IntegerField(default=0),
        ),
    ]
