# Generated by Django 4.2.8 on 2024-01-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0024_payroll_age_payroll_salaryrange'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
