# Generated by Django 4.2.8 on 2024-01-12 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0027_lastdeletedreference_delete_referencenumbercounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.company_details'),
        ),
    ]
